# .github/workflows/delete-merged-branches.yml

name: Delete merged branches

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  delete-merged-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all remote branches
        run: |
          echo "Fetching all remote branches..."
          git fetch --all --prune
          git branch -r
          echo "Fetched branches: "
          git branch -r

      - name: Identify and delete merged branches
        run: |
          echo "Identifying branches to delete..."
          
          # List branches merged into origin/main, excluding main, master, and develop
          branches_to_delete=$(git branch -r --merged | egrep -v "(^\*|master|main|develop)" | sed 's/origin\///')
          
          # Check if there are any branches to delete
          if [ -z "$branches_to_delete" ]; then
            echo "No merged branches found to delete."
          else
            echo "Branches to delete: $branches_to_delete"
            # Loop through each branch and delete it
            echo "$branches_to_delete" | xargs -n 1 git push origin --delete
          fi
          
          echo "Branch deletion process completed."
