name: Delete Merged and Closed Branches

on:
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at midnight
  workflow_dispatch: # Allows manual trigger

jobs:
  delete-branches:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Defined once here

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Set up GitHub CLI authentication
        run: gh auth setup-git

      - name: Fetch merged pull requests
        run: |
          gh pr list --state merged --json headRefName --jq '.[].headRefName' > merged_branches.txt

      - name: Delete merged branches
        run: |
          while read branch; do
            if [ "$branch" != "main" ]; then
              git push origin --delete "$branch" 2>/dev/null || echo "Branch $branch does not exist, skipping"
            fi
          done < merged_branches.txt

      - name: Fetch closed (stale) pull requests
        run: |
          gh pr list --state closed --json headRefName --jq '.[].headRefName' > closed_branches.txt

      - name: Delete closed branches
        run: |
          while read branch; do
            if [ "$branch" != "main" ]; then
              git push origin --delete "$branch" 2>/dev/null || echo "Branch $branch does not exist, skipping"
            fi
          done < closed_branches.txt
