name: Delete Merged and Closed Branches

on:
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at midnight
  workflow_dispatch: # Allows manual trigger

jobs:
  delete-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Authenticate with GitHub CLI
        run: gh auth login --with-token ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch merged pull requests
        run: |
          gh pr list --state merged --json headRefName --jq '.[].headRefName' > merged_branches.txt

      - name: Delete merged branches
        run: |
          while read branch; do
            if [ "$branch" != "main" ] && [ "$branch" != "master" ]; then
              git push origin --delete "$branch"
            fi
          done < merged_branches.txt

      - name: Fetch closed (stale) pull requests
        run: |
          gh pr list --state closed --json headRefName --jq '.[].headRefName' > closed_branches.txt

      - name: Delete closed branches
        run: |
          while read branch; do
            if [ "$branch" != "main" ] && [ "$branch" != "master" ]; then
              git push origin --delete "$branch"
            fi
          done < closed_branches.txt
